# Generated by Django 3.2 on 2022-10-03 08:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_alter_orderlines_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlines',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0, 'Цена не может быть меньше нуля')], verbose_name='Цена'),
        ),
    ]
