# Generated by Django 3.2 on 2022-10-03 09:30

from django.db import migrations, models
import foodcartapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_alter_order_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_num',
            field=models.CharField(default=foodcartapp.models.order_mum_default, max_length=20, unique=True, verbose_name='Номер заказа'),
        ),
    ]
