# Generated by Django 3.2 on 2022-10-03 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_alter_order_order_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlines',
            name='position_num',
        ),
    ]
