# Generated by Django 3.2 on 2022-10-03 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_remove_orderlines_position_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlines',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lines', to='foodcartapp.product', verbose_name='Продукт'),
        ),
    ]
