# Generated by Django 3.2 on 2022-10-05 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_alter_order_restaurant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
