# Generated by Django 3.2 on 2022-10-07 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0059_remove_order_order_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='restaurant',
            new_name='cooked_in_restaurant',
        ),
    ]
