# Generated by Django 3.2 on 2023-03-06 09:38

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('foodcartapp', '0060_rename_restaurant_order_cooked_in_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Добавьте тэги для быстрого поиска', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Теги'),
        ),
    ]
